lab_06/urls.py
from django.urls import path
from lab_06.views import Homepage, BioViews

app_name = "home"
 
urlpatterns = [
    path('', Homepage, name='index'),
    path("biodata/", BioViews, name="biodata")
]

praktikum/urls.py
from django.urls import path,include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include("lab_06.urls")),
    path('story9/', include("story9.urls")),
    path('story10/', include("story10.urls")),
]

story10/urls.py
from django.urls import path
from story10.views import validation_form, daftar_form, retrieve_all, delete_user

app_name = "story10"

urlpatterns = [
    path("",validation_form, name="validation"),
    path("daftar", daftar_form, name="daftar"),
    path("get_user", retrieve_all, name="retrieve"),
    path("delete/<slug_email>", delete_user, name="")
]

story9/urls.py
from django.urls import path
from story9.views import elektronik_views, nembak_data, masuk_views, keluar_views

app_name = "story9"

urlpatterns = [
    path("", elektronik_views, name="index"),
    path("get_data", nembak_data, name="nembak"),
    path("masuk", masuk_views, name="masuk"),
    path("keluar", keluar_views, name="keluar"),
]

lab_06/models.py
from django.db import models

class StatusModel(models.Model):
    email = models.EmailField(max_length=200)
    status = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

story10/models.py
from django.db import models
from django.template.defaultfilters import slugify

class UserModel(models.Model):
    email = models.EmailField(max_length=120)
    nama = models.CharField(max_length=100)
    password = models.CharField(max_length=120)
    slug = models.SlugField(unique=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(UserModel,self).save(*args,**kwargs)

story9/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify



# Create your models here.
class UserInfo(models.Model) :
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    slug = models.SlugField(unique=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(UserInfo,self).save(*args,**kwargs)

    def __str__(self) :
        return self.user.username

lab_06/forms.py
from django import forms
from lab_06.models import StatusModel

class StatusForm(forms.ModelForm):
    email = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
            "id":"email",
            "placeholder":"email"
        }
    ))
    status = forms.CharField(label="", widget=forms.Textarea(
        attrs = {
            "id":"status",
            "placeholder":"status....",
        }
    ))

    class Meta:
        model = StatusModel
        fields = ("email", "status")

story10/forms.py
from django import forms
from story10.models import UserModel


class DaftarForm(forms.ModelForm):
    email = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
                'id' : 'email_form',
                'type' : 'email',
                'name' : 'email',
                }
    ))
    password = forms.CharField(label="", widget=forms.PasswordInput(
    attrs = {
            "id" : "password",
            }
    ))
    username = forms.CharField(label="", widget=forms.TextInput(
    attrs = {
            "id" : "name_form",
            "required": "true",
            }
    ))
    class Meta:
        model = UserModel
        fields = ("email", "password", "username")

lab_06/views.py
from django.shortcuts import render, redirect
from lab_06.models import StatusModel
from lab_06.forms import StatusForm

def Homepage(request):
    form = StatusForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save()
            return redirect("home:index")
    return render(request, "homepage.html", {
        'form':StatusForm(),
        'status':StatusModel.objects.order_by("-date"),
    })

def BioViews(request):
    return render(request, "biodata.html")

story10/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from story10.forms import DaftarForm
from story10.models import UserModel
from django.contrib import messages

def validation_form(request):
    email = request.GET.get('email',None)
    data = {
        'sudah_ada' : UserModel.objects.filter(email__iexact=email).exists()
    }

    return JsonResponse(data, safe=False)

def daftar_form(request):
    form = DaftarForm(request.POST)
    
    if request.method == "POST" :
        if form.is_valid():
            instance = form.save(commit=False)
            instance.set_password = request.POST["password"]
            instance.save()
            print("berhasil")
        else :
            print(form.errors)
    
    return render(request, "story10.html", {
        "form" : DaftarForm,
    })

def retrieve_all(request):
    all_user = UserModel.objects.all()
    data = []
    for i in range(len(all_user)):
        data.append({
            "email" : all_user[i].email,
            "nama"  : all_user[i].nama,
            "slug"  : all_user[i].slug,
        })

    return JsonResponse(data, safe=False)

def delete_user(request, slug_email):

    user_obj = UserModel.objects.get(slug=slug_email)
    isSuccess = False
    if request.method == "POST":
        user_obj.delete()
        isSuccess = True

    data = {
        "sukses" : isSuccess
    }

    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import requests
from django.contrib.auth import authenticate, login, logout
from story9.models import UserInfo
from django.contrib.auth.models import User

def elektronik_views(request):
    
    return render(request, "story9.html")

def nembak_data(request):
    data_list = []
    num = []
    response = requests.get("https://enterkomputer.com/api/product/notebook.json")
    data = response.json()

    for dataku in range(1000,1100) :
        data_list.append(data[dataku])
    
    return JsonResponse(data_list, safe=False)

def masuk_views(request) :

    if request.method == "POST" :
        username = request.POST.get("username")     # grab the input from the user
        password = request.POST.get("password")

        request.session['local_password'] = password
        if username == "" or password == "" :
            messages.warning(request, "Please Input Your Username and Password")
            return redirect("story9:index") 
        else :
            user = authenticate(username = username, password = password)   # return true if username and pass verified
            print(user)
            if user :
                if user.is_active :
                    login(request, user)
                    
                    return redirect("story9:index") 
                else :
                    messages.warning(request, "Invalid username or password")
                    return HttpResponse("the username or password are invalid")
            else :
                print("there any user failed login")
                print("username: {} and pass: {}".format(username,password))
                messages.warning(request, "Invalid username or password")
                return redirect("story9:index") 

    else :
        return redirect("story9:index") 


@login_required
def keluar_views(request) :
    logout(request)
    return redirect("story9:masuk")

templates/biodata.html
{% extends 'homepage.html' %}
{% load static %}

    
    {% block body %}
        
    <div class="container">
        <div class="content row">
            <div id = "foto">
                <img src="{% static 'img/angga.png' %}" id="angga">
                <img>
                <h1 id="nama">Anggardha Febriano</h1>
                <h1 id="npm">1806235800</h1>
                <a href="{% url 'home:index' %}"><button id="myBtn" class="button dark">Home</button></a>
            </div>
            <div id="foto" style="justify-content:unset;">
                <div onclick="accordion(1)" class="accordion accordion1">
                    <div class="title">
                        <div class="grid-item">
                            <p>Aktivitas</p>
                        </div>
                        <div class="grid-item"></div>
                        <div class="grid-item plus plus1">
                        </div>
                    </div>
                    <div class="accordion-content accordion-content1">
                            <h1>- Staff Bem PTI</h1>
                            <h1>- Kuliah</h1>
                            <h1>- Makan</h1>
                            <h1>- Minum</h1>
                    </div>
                </div>
                <div onclick="accordion(2)" class="accordion accordion2">
                    <div class="title">
                        <div class="grid-item">
                            <p>Organisasi</p>
                        </div>
                        <div class="grid-item"></div>
                        <div class="grid-item plus plus2">
                        </div>
                    </div>
                    <div class="accordion-content accordion-content2">
                            <h1>- Staff Bem PTI</h1>
                            <h1>- Staff Pemira Fasilkom</h1>
                            <h1>- Staff Olimpiade UI</h1>
                    </div>
                </div>
                <div onclick="accordion(3)" class="accordion accordion3">
                    <div class="title">
                        <div class="grid-item">
                            <p>Prestasi</p>
                        </div>
                        <div class="grid-item"></div>
                        <div class="grid-item plus plus3">
                        </div>
                    </div>
                    <div class="accordion-content accordion-content3">
                        <h1>- OSP Biologi 2017</h1>
                        <h1>- Juara Taekwondo</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
        

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Landing Page</title>
</head>

<body>

    {% block body %}
    <div class="load">
        <div id="loading"></div>
    </div>
    <div id="wrapper">
        <div class="container">
            <div class="content">
                <div id="greet">
                    <h1>Hello,Welcome :).</h1>
                </div>
                <div class="status">
                    {% for s in status %}
                    <div class="status-content">
                        <i class="material-icons">comment</i>
                        <p>{{s.email}},{{s.date | timesince}} ago<br>{{s.status}}</p>
                    </div>
                    {% empty %}
                    <div class="status-content">
                        <h1 style="font-size:5vw"><i class="material-icons" style="font-size:5vw">warning</i>There is no
                            Status available...</h1>
                    </div>
                    {% endfor %}
                </div>
                <div>
                    <button id="myBtn" class="button dark">Update Status</button>
                    <button onclick="changeTheme();" onmouseover="themePreview()" ; onmouseout="themePreview();"
                        class="button theme dark">Change Theme</button>
                    <a href="{% url 'home:biodata' %}"><button class="button dark">Biodata</button></a>
                    <a href="{% url 'story9:index' %}" id="toko"><button class="button dark">Toko Laptop</button></a>
                    <a href="{% url 'story10:daftar' %}" id="toko"><button class="button dark">Subscribe</button></a>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal">

            <!-- Modal content -->
            <div style="width:40%">
                <span class="close">&times;</span>
                <h1 style="color:white">What is on your mind?</h1>
                <form method="POST">
                    <div class="content">
                        {% csrf_token %}
                        {{form}}
                        <input type="submit" value="Post" class="button light">
                    </div>
                </form>
            </div>

        </div>
        <footer id="footer">
            <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <div class="wrap">
                <a class="item" href="https://id.linkedin.com/in/anggardha-febriano-369672128">
                    <i class='fa fa-linkedin-square' style="color: #333333;font-size: 24px"></i>
                </a>
                <a class="item" href="https://gitlab.com/anggardhanoano">
                    <i class='fa fa-gitlab' style="color: #333333;font-size: 24px"></i>
                </a>
                <a class="item" href="mailto:anggardhanoano@gmail.com?Subject=Hello">
                    <i class="fa fa-envelope" style="color: #333333;font-size: 24px"></i>
                </a>

            </div>
            <p style="color:#333333">Anggardha Febriano <i class="fa fa-copyright"></i>2019</p>
        </footer>
    </div>

    {% endblock body %}


    <!-- js stuff -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.js"></script>
    {% block js %}{% endblock js %}
    <script src="{% static 'js/base.js' %}"></script>
</body>

</html>

templates/story10.html
{% extends 'homepage.html' %}
{% load static %}

{% block body %}
<div class="content" style="padding-top:100px">
    <h1>Subscribe to My Website</h1>
    <form method=POST>
        {% csrf_token %}
        <p>Email : {{form.email}}</p>
        <p id="emailAlert" style="color:red">Email Sudah Dipakai</p>
        <p id="emailNotValid" style="color:red">Email Tidak Valid</p>
        <p id="emailKosong" style="color:red">Email wajib diisi</p>
        <p id="emailValid" style="color:green">Email Bisa Dipakai</p>
        <p>Name : {{form.username}}</p>
        <p>Password : {{form.password}}</p>
        <p id="passAlert" style="color:red">Password harus memiliki minimal 7 karakter</p>
        <p id="passNotValid" style="color:red">Password harus mengandung huruf dan angka</p>
        <p id="passValid" style="color:green">Password Bisa Dipakai</p>
        <p id="success" style="color:green">Anda berhasil Daftar, silahkan daftar lagi</p>
        <p id="error" style="color:red">Anda Gagal Daftar</p>
    </form>
    <button class="button" type="button" onclick="daftarPost()" disabled id="daftar">Daftar</button><br>
    <button onclick="showData()" class="button">Show Data</button>
    <div id="data">
        <p>Subscriber</p>
    </div>
</div>


{% endblock body %}

{% block js %}
<script src="{% static 'js/story10.js' %}"></script>
{% endblock js %}

templates/story9.html
{% extends 'homepage.html' %}
{% load static %}

{% block body %}



<div class="container-story9">
    {% if user.is_authenticated %}
    <h3>Hello, {{user.username}}</h3>
    <a href="{% url 'story9:keluar' %}">Logout</a>
    {% else %}
    <form method="POST" action="{% url 'story9:masuk' %}">
        {% csrf_token %}
        <input type="input" name="username">
        <input type="password" name="password">
        <button type="submit">Login</button>
        <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
    </form>
    {% endif %}
    <h1 style="font-size:5em;text-align: center;">Electronics Stuff</h1>
</div>
<div>
    <div class="container-grid">
        <div class="grid-item-story9">
            <div class="l0">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i0">
                <p id="text0"></p>
                <p id="price0"></p>
                <p id="brand0"></p>
                <p id="category0"></p>
                <p id="desc0"></p>
                <button class="button" onclick="addWishList(0)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l1">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i1">
                <p id="text1"></p>
                <p id="price1"></p>
                <p id="brand1"></p>
                <p id="category1"></p>
                <p id="desc1"></p>
                <button class="button" onclick="addWishList(1)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l2">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i2">
                <p id="text2"></p>
                <p id="price2"></p>
                <p id="brand2"></p>
                <p id="category2"></p>
                <p id="desc2"></p>
                <button class="button" onclick="addWishList(2)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l3">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i3">
                <p id="text3"></p>
                <p id="price3"></p>
                <p id="brand3"></p>
                <p id="category3"></p>
                <p id="desc3"></p>
                <button class="button" onclick="addWishList(3)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l4">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i4">
                <p id="text4"></p>
                <p id="price4"></p>
                <p id="brand4"></p>
                <p id="category4"></p>
                <p id="desc4"></p>
                <button class="button" onclick="addWishList(4)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l5">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i5">
                <p id="text5"></p>
                <p id="price5"></p>
                <p id="brand5"></p>
                <p id="category5"></p>
                <p id="desc5"></p>
                <button class="button" onclick="addWishList(5)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l6">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i6">
                <p id="text6"></p>
                <p id="price6"></p>
                <p id="brand6"></p>
                <p id="category6"></p>
                <p id="desc6"></p>
                <button class="button" onclick="addWishList(6)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l7">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i7">
                <p id="text7"></p>
                <p id="price7"></p>
                <p id="brand7"></p>
                <p id="category7"></p>
                <p id="desc7"></p>
                <button class="button" onclick="addWishList(7)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l8">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i8">
                <p id="text8"></p>
                <p id="price8"></p>
                <p id="brand8"></p>
                <p id="category8"></p>
                <p id="desc8"></p>
                <button class="button" onclick="addWishList(8)">Add</button>
            </div>
        </div>
        <div class="grid-item-story9">
            <div class="l9">
                <div class="load-stuff">
                    <div id="loading-stuff"></div>
                </div>
            </div>
            <div class="wrap-stuff i9">
                <p id="text9"></p>
                <p id="price9"></p>
                <p id="brand9"></p>
                <p id="category9"></p>
                <p id="desc9"></p>
                <button class="button" onclick="addWishList(9)">Add</button>
            </div>
        </div>
    </div>
</div>
<div class="container-story9">
    <div style="display:flex">
        <button class="button" style="margin:2px;" onclick="getPage(0)">1</button>
        <button class="button" style="margin:2px;" onclick="getPage(1)">2</button>
        <button class="button" style="margin:2px;" onclick="getPage(2)">3</button>
        <button class="button" style="margin:2px;" onclick="getPage(3)">4</button>
        <button class="button" style="margin:2px;" onclick="getPage(4)">5</button>
        <button class="button" style="margin:2px;" onclick="getPage(5)">6</button>
        <button class="button" style="margin:2px;" onclick="getPage(6)">7</button>
        <button class="button" style="margin:2px;" onclick="getPage(7)">8</button>
        <button class="button" style="margin:2px;" onclick="getPage(8)">9</button>
        <button class="button" style="margin:2px;" onclick="getPage(9)">10</button>
    </div>
    <!-- <button class="button" onclick="onRefresh()" style="width:80%;margin-bottom:50px;background-color:orange">Generate Other Stuff</button> -->
    <div id="barang">
        <h1 style="text-align:center">Your Wishlist</h1>
        <p id="justify" style="text-align:center">No Item in Wishlist</p>
    </div>
    <h1 id="total-price">Total Price</h1>
    {% if user.is_authenticated %}
    <p id="wish">Rp 0</p>
    {% else %}
    <p>Please Login to see the total price</p>
    {% endif %}
</div>


{% endblock body %}


{% block js %}
<script src="{% static 'js/story9.js' %}"></script>
{% endblock js %}